# Generated by Django 6.0.1 on 2026-01-18 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modo_visual', models.CharField(choices=[('minimalista', 'Modo Minimalista'), ('avanzado', 'Modo Visual Avanzado')], default='minimalista', max_length=20, verbose_name='Modo visual')),
                ('paleta_colores', models.CharField(choices=[('nude', 'Nude (Tonos neutros)'), ('azul', 'Azul Sereno'), ('verde', 'Verde Natural'), ('purpura', 'Púrpura Suave')], default='nude', max_length=20, verbose_name='Paleta de colores')),
                ('tamano_texto', models.CharField(choices=[('normal', 'Normal'), ('grande', 'Grande'), ('muy_grande', 'Muy Grande')], default='normal', max_length=20, verbose_name='Tamaño de texto')),
                ('alto_contraste', models.BooleanField(default=False, verbose_name='Modo alto contraste')),
                ('recordatorio_anticipado', models.BooleanField(default=True, verbose_name='Recordatorio 5 minutos antes')),
                ('notificaciones_activas', models.BooleanField(default=True, verbose_name='Notificaciones activas')),
                ('sonido_notificacion', models.BooleanField(default=True, verbose_name='Sonido en notificaciones')),
                ('backup_automatico', models.BooleanField(default=False, verbose_name='Backup automático')),
                ('frecuencia_backup_dias', models.PositiveIntegerField(default=7, verbose_name='Frecuencia de backup (días)')),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True, verbose_name='Último backup')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuración de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del medicamento')),
                ('color', models.CharField(blank=True, help_text='Código hexadecimal (ej: #FF5733)', max_length=7, null=True, verbose_name='Color identificador')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono identificador')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora_programada', models.DateTimeField(verbose_name='Hora programada')),
                ('hora_confirmada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de confirmación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada a tiempo'), ('tarde', 'Confirmada tarde'), ('no_tomada', 'No tomada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Toma',
                'verbose_name_plural': 'Tomas',
                'ordering': ['-hora_programada'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('principal', 'Notificación principal'), ('recordatorio', 'Recordatorio anticipado')], default='principal', max_length=20, verbose_name='Tipo de notificación')),
                ('hora_programada', models.DateTimeField(verbose_name='Hora programada')),
                ('enviada', models.BooleanField(default=False, verbose_name='Enviada')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('toma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='medicamentos.toma')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-hora_programada'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('duracion_dias', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para tratamiento indefinido', null=True, verbose_name='Duración en días')),
                ('es_indefinido', models.BooleanField(default=False, verbose_name='Tratamiento indefinido')),
                ('frecuencia_horas', models.DecimalField(decimal_places=2, help_text='Intervalo entre tomas en horas', max_digits=5, verbose_name='Frecuencia (horas)')),
                ('modo_calculo', models.CharField(choices=[('programada', 'Desde hora programada'), ('confirmacion', 'Desde hora de confirmación')], default='programada', help_text='Determina cómo se calcula la siguiente toma', max_length=20, verbose_name='Modo de cálculo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado')], default='activo', max_length=20, verbose_name='Estado del tratamiento')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='medicamentos.medicamento')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='toma',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='medicamentos.tratamiento'),
        ),
    ]
