# Generated by Django 5.2.7 on 2026-01-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toma',
            name='medicamento_nombre_historico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del medicamento (historico)'),
        ),
        migrations.AddField(
            model_name='toma',
            name='tratamiento_frecuencia_historica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Frecuencia del tratamiento (historico)'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='medicamento_nombre_historico',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del medicamento (historico)'),
        ),
        migrations.AlterField(
            model_name='toma',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tomas', to='medicamentos.tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='medicamentos.medicamento'),
        ),
    ]
