# Generated by Django 5.2.7 on 2026-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_toma_medicamento_nombre_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='telegram_activo',
            field=models.BooleanField(default=False, verbose_name='Notificaciones por Telegram'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='telegram_vinculado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vinculacion Telegram'),
        ),
    ]
